# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme: "mount_holyoke"
  color: "mount_holyoke"
  font: native
  font_size: L

# SEO

# marketing:
#   seo:
#     site_type: Organization
#     local_business_type: ''
#     org_name: ''
#     description: 'A highly-customizable Hugo research group theme powered by Wowchemy website builder.'
#     twitter: 'GetResearchDev'
#   analytics:
#     google_analytics: ''
#     baidu_tongji: ''
#     google_tag_manager: ''
#     microsoft_clarity: ''
#   verification:
#     google: ''
#     baidu: ''

# Site header
header:
  navbar:
    enable: true
    align: r 
    show_title: true
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: false
    logo:
      filename: "logo.svg"  # Ensure "icon.png" is in `assets/media/`
      height: 90px  # Set a reasonable height (e.g., 50px for a navbar logo)
    button:
      enable: true
      text: "Get Started"
      url: "https://hugoblox.com/templates/"


# Site footer

footer:
  copyright:
    notice: '© {year} Mount Holyoke College Undergraduate Law Journal. <br>This publication is published by students at Mount Holyoke College, and MHC is not responsible for its contents'
    license:
      enable: false
      allow_derivatives: false
      share_alike: false
      allow_commercial: false
  social:
    - name: Instagram
      brand: instagram
      url: "https://instagram.com/yourhandle"
    - name: LinkedIn
      icon: fab fa-linkedin

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    enable: false
    extra_languages:
      - r
      - latex
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/<username>/<repository>'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: 'mapnik'
    api_key: ''
    zoom: 15

# Extensions

extensions:
  decap_cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Citation style

publications:
  date_format: January 2006
  citation_style: apa

params:
  custom_css:
    - css/themes/mount_holyoke.css
  color: "mount_holyoke"  # Ensure it uses our custom theme

# header:
#   navbar:
#     enable: true
#     show_logo: true

# logo:
#   path: "/assets/media/icon.png" # Adjust the path based on where your logo is stored
#   alt: "Mount Holyoke Law Journal Logo"
#   height: 40px


